name: Lint And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: testing
      SECRET_KEY: Myb6Bh1c2XDBA3xfYW6pwUH2NLZ3Kmkt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install linting tools
        run: pip install pylint isort autopep8

      - name: Install test tools
        run: pip install pytest pytest-django

      - name: Check import order with isort
        run: isort src --check-only --diff

      - name: Check code format with autopep8
        run: autopep8 --diff --exit-code -r src

      - name: Run pylint
        run: pylint src

      - name: Run tests with pytest
        run: pytest -v src
