name: Lint And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: UtBwzubmFGXykwWyiLBa0lF0PlXMuA21
      DB_ENGINE: django.db.backends.sqlite3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install linting tools
        run: pip install pylint isort black

      - name: Install test tools
        run: pip install pytest pytest-django

      - name: Check import order with isort
        run: isort src --check-only --diff

      - name: Check code format with Black
        run: black --check --diff src

      - name: Run pylint
        run: pylint src

      - name: Run tests with pytest
        run: pytest -v src
